apiVersion: v1
kind: Namespace
metadata:
  name: demo-helloworld-app
  labels:
    app: helloworld

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: helloworld-sa
  namespace: demo-helloworld-app
  labels:
    app: helloworld

---

apiVersion: v1
kind: Secret
metadata:
  name: tls-ca
  namespace: demo-helloworld-app
  labels:
    app: helloworld
data:
  cacerts.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5RENDQWR5Z0F3SUJBZ0lVRWtXRDAzSWptd2d1Y3ZVSVBUQVByWGt6N0pBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0VqRVFNQTRHQTFVRUF4TUhiWFJzY3kxallUQWVGdzB5TVRFeU1UQXhNak0wTURCYUZ3MHlOakV5TURreApNak0wTURCYU1CSXhFREFPQmdOVkJBTVRCMjEwYkhNdFkyRXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCCkR3QXdnZ0VLQW9JQkFRREZTVEVPNllMTC9RdW1ZaUZ0aWJUUExwWEpzMWdUM2V2RnNkS2VzUDdFaUMrRXRZOUUKNUdCNDV2M0lJVGp4SVEwWTlzWjlzSjMwaCtyTGFGNHdxeU5CbXVuOVR6TjQvVS9iVCtueTl4eCtNdFNRczlsZApkd2k5dlFQQ2pDQlYrR2drUXQ1WFR0aHdBbS9ieTYyS1h1b3pKUk5GMTl5cjdkc05oSkM0SG44b3NsVmpkN1ZUCkZuNUlFL3IxVVl2NUk5bUdYZmFoeXFrSGo5cnR4d2ZZTlk1OEFwaXhDZGExMFdPNml1WU5TM2czZDdKajNrakMKSTkxanNwb29CU21DeDVySlpNRVN4VlQzWExSQTNBcnljbVlqVE92MFN0cFRQZkpaSU0wVE9icmFra0ZhTzFRKwpLeFNjNVQwQm9DeDBnSzViMWUxc3FjZ1ZqbmI2WmtJUW9Td0hBZ01CQUFHalFqQkFNQTRHQTFVZER3RUIvd1FFCkF3SUJCakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlFiVi9odVZKYmYvZVJPSXA1SGphQmoKTDBIaitEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFISTF0RXZ0a0Ryemo1ZGQ5Qm5aQ1NydDIxemk2Mmc0NgpxZ1REQXQxMTgrdGJMWjN1d25oWjdpclQ2ZjY5K0ZWRjV2WUhEZG9oVjQvdkVXVDRTSDhnQy9qc21NemQwZ3dXClpxNm80UzF0Z1hGT2R1N203R0FVbG9WTld3bWN6LzNzbHhuVS81R25naW9oc3c3YXhPRTNtN2RGVzEvVWdDeUQKY2xjT0p5VVUrclVGa05kdlZRLzQram5YNUNUc0t1YmFuL29xazd2cGtqWnlQOXBZdEh5b20wYVZUaGdQMmxPdgpCNkNiSGdtNXFQUFpxNDkzYmRyZEpkS3kzMEIyN3A0UUhqQ25nT3kyQzhYd3FTa2J4c29pQWt0MzRMb1FjeUM1ClNzQU9TdURBU2lKeTRiZlZlSWlZUHM1Mmg5cTJlRDdEUjdsNEJJVHR0L3hTdUtsbjk0RkpIQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
type: Opaque

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-app
  namespace: demo-helloworld-app
  labels:
    app: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image:
            swr.cn-east-3.myhuaweicloud.com/vipexcc/kic/k8spod-test:alpine
          env:
            - name: TZ
              value: Asia/Shanghai
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: stg
              mountPath: /stg
          #workingDir: /stg
      serviceAccountName: helloworld-sa
      restartPolicy: Always
      volumes:
        - name: stg
          hostPath:
            path: /stg
            type: DirectoryOrCreate
  #strategy:
  #  type: RollingUpdate
  #  rollingUpdate:
  #    maxUnavailable: 1
  #    maxSurge: 1

---

apiVersion: v1
kind: Service
metadata:
  name: helloworld-srv
  namespace: demo-helloworld-app
  labels:
    app: helloworld
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8080
  selector:
    app: helloworld

---

apiVersion: v1
kind: Secret
metadata:
  name: tls-helloworld-ing
  namespace: demo-helloworld-app
  labels:
    app: helloworld
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURYRENDQWtTZ0F3SUJBZ0lVTUh0bHBmYS9pUFhJN0NyQWVicFl1VHFVRk44d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0VqRVFNQTRHQTFVRUF4TUhiWFJzY3kxallUQWVGdzB5TVRFeU1UZ3dNelEzTURCYUZ3MHlOREV5TVRjdwpNelEzTURCYU1CRXhEekFOQmdOVkJBTVRCbk5sY25abGNqQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQCkFEQ0NBUW9DZ2dFQkFMRmhEcU4zRGxZNlRsbTZtbVRXaVdOR1E0Q2g0OTB0bURZa2JNOTVqYkNQWU5FSVdmQzUKQUFuaVBEaVAweVM4bUd5czJOdlVVMTJrQ3QxbnM0VElMc2ZFYkdyREtEYWd0Z3RaSHJ2ekUzbzZmajRaUDk1cwpPR2pXQ0QrYUlmejhlQWdwTjRFM2lCSVhhbzhWZy9aVytEV2lSQTJCR3dSemxYZkxRc01vWlRRdHo2Z0syN2VRCjVBZFUwems5QlMzZnJIMHlITDkramZvQWVpb0lTOUJXY1Zkdm5vanBFK1hZUFM4S2dZcXhUbnphbUVLbkZNbzEKT3JIK3puSXluNWVmNURKRCtBMWdGd0xDSzArTVU4a1BtaVliNmcwLzJjNjd2MExTN3pNcDZiMGJYaFBoTGRNagpPMVRyVjdUQzllM0FYak5yc0hrQWdSb1B6TGs4cW9pT0h2a0NBd0VBQWFPQnFqQ0JwekFPQmdOVkhROEJBZjhFCkJBTUNCYUF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01Bd0dBMVVkRXdFQi93UUMKTUFBd0hRWURWUjBPQkJZRUZCeUFHTnhLVDRZK1BBWmttNmJGK0k3REpoRllNQjhHQTFVZEl3UVlNQmFBRkJ0WAorRzVVbHQvOTVFNGlua2VOb0dNdlFlUDRNQ2dHQTFVZEVRUWhNQitDREhSemRDNTJhWEJsZUM1alk0SUpiRzlqCllXeG9iM04waHdSL0FBQUJNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNZb2RGU0xCZzZ3d1JqV3I4MzhpcFQKSGJqUURMUDAzaTNFeG82ZFVKME82MmRJNmtoUE9uYThnSkphWnZhNnpQMTVVbktXU1VCaEorNjlPdEg3QUtydQpZZHk5aVBncGRCSG4rMVU3QTQxMkVSc09KS1BIc04vSnozd21id2xpazRTR2hFWktMeHRkTkJYaFp3NnZZcEp2ClB1T0ZjS1EvZzQ2NnhqZXlidXIrc1djTmdVMU1xNzJLNUpyN0tRVG43RDJNc0g2VFZkSFNuL1p4ZWxoZ1JVV0cKRjRrdG8vL1Y3SUtOYXVLQ05oN3lLSkJielpUK3VQTlZ5UC9HbTVRY1F4eUZZVFRPOFNvR1M2TjBuK2IwVVpjQwpMRW8xRFA4Slh6ajVsSzdmakJ6NlBYb1dZUlJ2WEdZb3RVL0xITVdhM3lqb1grbkNsQXlRekdpWXdEeUlUS2pQCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBc1dFT28zY09WanBPV2JxYVpOYUpZMFpEZ0tIajNTMllOaVJzejNtTnNJOWcwUWhaCjhMa0FDZUk4T0kvVEpMeVliS3pZMjlSVFhhUUszV2V6aE1ndXg4UnNhc01vTnFDMkMxa2V1L01UZWpwK1Boay8KM213NGFOWUlQNW9oL1B4NENDazNnVGVJRWhkcWp4V0Q5bGI0TmFKRURZRWJCSE9WZDh0Q3d5aGxOQzNQcUFyYgp0NURrQjFUVE9UMEZMZCtzZlRJY3YzNk4rZ0I2S2doTDBGWnhWMitlaU9rVDVkZzlMd3FCaXJGT2ZOcVlRcWNVCnlqVTZzZjdPY2pLZmw1L2tNa1A0RFdBWEFzSXJUNHhUeVErYUpodnFEVC9aenJ1L1F0THZNeW5wdlJ0ZUUrRXQKMHlNN1ZPdFh0TUwxN2NCZU0ydXdlUUNCR2cvTXVUeXFpSTRlK1FJREFRQUJBb0lCQUNMQ25XYkZUd2J3MkNmWApYS2hFTHBwSXk3T3FoZ2Z6Qm5BZHhVRUhWZy95bVF0OXNucHRGcWZaTU9uNHJXejJsSHcvaHlQVlFSMEpwNk5wCnpoRklWWHFLY0tDZmJBTUFqWXc5dzdzYlVJYlViYWJudGM5MXI3eERyVXdoZldXaGFEaFpNMnBjSW90QkVYM0cKdnB5SXdJMXFKaUhyV2dzT1I0MDVSUFVQdG4xNTVUTzRtSDJQRFdKWS82SE81MllIZVdBWTBHOFp5VnF2TDZaTAphR3ZENWx4RzhKTWVHTVRZMEo0dUdZdnJQR0t2SVQ5NXFFNjJlbGFjOXhtdXRHblRCQnhHMXlVTml6Ylg4OWNECkVhQTlPeU8zZTFwc2dXWURtd2FOZDF2OTdacHRCOHJUdjBrNkZMdmNOZWkrZTZIRVc1WjJCWDQxTm5jOWorcmUKWHlrU2JQMENnWUVBelg3QllrNHRUb2xDUGgwVjhSdFhVR0RGclNjUTEzYWFpYnUvelFQOS9xdFdob21XT0JoMgp1c0U4Z2NEWXlrWXVEQjFJWXdKclBtZ2ZsYzd1Z2krNXFvc2xKVEdvK0FNTzJLRzdFUk1QeWp2ZHg5cGF3bXJLCkNCSW9QVkxuNExwMkFyMlNtUTA2NWxaM1FJaUZPa1NQRHhuUWNaeGJNU1VVVURxeXZLU1ArWjhDZ1lFQTNQbFAKN2FoM1c5RjIvRTZoNGJrT1NDV01rOHVtN243c0pFUmM1SGtqZTd6K3lQdE53Z3pHdUY0cHNsUUx2UUVmcEdSMQp1TENYV3NUejBWb09VRTNsNkZjUi81SDRJeWc0bE9XeENUempsRllSYkNIZitOelJiRnU3ZGRRYzdZNDBWUVZ0CmlPN3hQaXY3VFFoa3kxZmRzK2V1bE41T1dkcktNRkpTVU1VQlVHY0NnWUVBcVdoeDdLVWVYTHh6UzltV21TbzkKRlJweVhJajBMV3l0Z2hheHpFWWFRclRscEF3Uk56V1R5K282QTQ0RUt0MG9ZUHhUREt5VjFPRHFDUXFMUGZBeQpWQkphRVF1YmpMcVlwcWJPSFFsbDN3YnpreXJEMzd0Qnl0Mk5KdUVPSUFvWDk3SnBCSndQam95QnkwWEE3NFJOCm05bGdLZ2tJZEw5b3U2dG9ablFUN1drQ2dZRUFyT3Q0VGIwNGNpU3ZYTy9YcEVEaFdUbnhFVE1iMWFTQy9EcDMKQ3Q5MUVmNnF6dkpCUGlvclU5bHovYlhoWGExRWFxdW1wN21oSjRuYVZxaUhiUFlZaE1HbU52MnVWU3pEWWxtQQpPWDlwaEFuNkprazM4SkkwVy94STdRTHBCRWowME5lbmlMR2JIUkRqM2J0RXpROWNVYzFxZzlxWEs1K1grMHBnCldnNWdZZDhDZ1lCL0R2cVZpdUVjeWVZMFFHVHQwVlp0cFd4eTdjYk92MEZKUHd2ZkkxM2FsNno3Q1Z2VDdXRE8KZ3V0RDZid1lERDFiOEZ5dWwyTmxtRlNPYTIwVm9renNjYmtxYXBPR0lvcG13MGtId3JxR0p3MGlEZ3piTXdQMwpaSG9rZXFzZDVISmtXV2NxZ0VvMjliZW5wazNiWmNRWEF2dXRsdS9PbWxSOWdFcS93dUVVelE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
type: kubernetes.io/tls

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld-ing
  namespace: demo-helloworld-app
  annotations:
    kubernetes.io/ingress.class: kong #nginx
  labels:
    app: helloworld
spec:
  rules:
    - host: tst.vipex.cc
      http:
        paths:
          - backend:
              service:
                name: helloworld-srv
                port:
                  number: 443
            path: /
            pathType: Prefix
  tls:
    - hosts:
      - tst.vipex.cc
      #secretName: helloworld-sn
      secretName: tls-helloworld-ing
